version: "3"
services:
  proxy-nginx:
    container_name: proxy-nginx
    image: nginx
    restart: unless-stopped
    networks:
      - fre
      - default
    ports:
      - "${PROXY_PORT}:80"
    volumes:
      - ./config/nginx-proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx-proxy/conf.d:/etc/nginx/conf.d
    environment:
      - DOMAIN=fre
      - TLD=localhost
  file-server:
    image: filebrowser/filebrowser:s6
    container_name: file-server
    restart: unless-stopped
    networks:
      - default
    volumes:
      - ./config/filebrowser.json:/config/settings.json
      - ./data/users:/srv
      - ./data/db:/database
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - fre

volumes:
  portainer_data:

networks:
  fre:
  default:
