version: "3"
services:
  proxy:
    container_name: "proxy"
    image: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - free_real_estate
  files:
    image: filebrowser/filebrowser:v2-alpine
    restart: always
    container_name: "files"
    volumes:
      - /home/fre/fre/users/data:/srv
      - /home/fre/fre/filebrowser/filebrowser.db:/database.db
      - /home/fre/fre/filebrowser/.filebrowser.json:/.filebrowser.json
    networks:
      - free_real_estate
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - free_real_estate
  
volumes:
  portainer_data:

networks:
  free_real_estate:
    driver: bridge
