version: "3"
services:
  proxy:
    container_name: "proxy"
    image: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - free_real_estate
  files:
    image: filebrowser/filebrowser:v2-alpine
    restart: always
    container_name: "files"
    volumes:
      - ./users/data:/srv
      - ./filebrowser/filebrowser.db:/database.db
      - ./filebrowser/.filebrowser.json:/.filebrowser.json
    networks:
      - free_real_estate
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - free_real_estate
    ports:
      - "8000:9000"
      - "9000:9000"
  netdata:
    image: netdata/netdata
    container_name: netdata
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - netdataconfig:/etc/netdata
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
    ports:
      - "19999:19999"
    networks:
      - free_real_estate

volumes:
  portainer_data:
  netdataconfig:
  netdatalib:
  netdatacache:

networks:
  free_real_estate:
    driver: bridge
