version: "3"
services:
  proxy-nginx:
    container_name: proxy-nginx
    image: nginx
    restart: unless-stopped
    networks:
      - fre
      - default
    ports:
      - "${PROXY_PORT}:80"
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/conf.d:/etc/nginx/conf.d
    environment:
      - DOMAIN=fre
      - TLD=localhost

  file-server:
    image: filebrowser/filebrowser:s6
    container_name: file-server
    restart: unless-stopped
    networks:
      - default
    volumes:
      - ./config/filebrowser.json:/config/settings.json
      - ./data/users:/srv
      - file_db:/database

volumes:
  file_db:
  code:

networks:
  fre:
  default:
