version: "3"
services:
  proxy-traefik:
    image: traefik:v2.5
    container_name: proxy-traefik
    restart: unless-stopped
    networks:
      - fre
      - default
    ports:
      - "${PROXY_PORT}:80"
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/traefik.yml:/etc/traefik/traefik.yml
    labels:
      - traefik.http.routers.api.rule=Host(`traefik.${HOSTNAME}`)
      - traefik.http.routers.api.service=api@internal
  file-server:
    image: filebrowser/filebrowser:s6
    container_name: file-server
    restart: unless-stopped
    networks:
      - default
    volumes:
      - ./config/filebrowser.json:/config/settings.json
      - ./data/users:/srv
      - ./data/db:/database
    labels:
      - traefik.http.routers.file-server.rule=Host(`files.${DOMAIN}`)

networks:
  fre:
  default:
